import { useMemo, useState } from 'react';
import { Download, Plus } from 'lucide-react';
import { EmptyCard, SummaryCard } from '../components/cards';
import { catalystMarkdown, downloadText } from '../features/export/markdown';
import type { Catalyst, Workspace } from '../types/domain';
import { PageHeader } from '../components/layout/AppShell';
import { saveCatalystRecord } from '../data/actions';
import { dateKey } from '../lib/calendar';

type View = 'month' | 'week' | 'day'; type Tab = 'calendar' | 'radar' | 'mappings';
const startOfWeek = (date: Date) => { const next = new Date(date); next.setDate(next.getDate() - next.getDay()); next.setHours(0, 0, 0, 0); return next; };
const category = (item: Catalyst) => /inflation|cpi|ppi/i.test(`${item.type} ${item.event}`) ? 'inflation' : /earnings/i.test(`${item.type} ${item.event}`) ? 'earnings' : /central|fed|rate|policy/i.test(`${item.type} ${item.event}`) ? 'policy' : 'macro';

function MonthCalendar({ focus, catalysts }: { focus: Date; catalysts: Catalyst[] }) {
  const first = new Date(focus.getFullYear(), focus.getMonth(), 1); const start = startOfWeek(first);
  const days = Array.from({ length: 42 }, (_, index) => { const day = new Date(start); day.setDate(start.getDate() + index); return day; });
  return <div className="month-calendar"><div className="weekday-row">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((day) => <span key={day}>{day}</span>)}</div><div className="month-grid">{days.map((day) => { const key = dateKey(day); const events = catalysts.filter((item) => item.date === key); return <article key={key} className={day.getMonth() === focus.getMonth() ? '' : 'outside'}><time dateTime={key}>{day.getDate()}</time><div>{events.slice(0, 2).map((item) => <span key={item.id} className={`event-chip ${category(item)}`} title={item.event}>{item.event}</span>)}{events.length > 2 && <small>+{events.length - 2} more</small>}</div></article>; })}</div></div>;
}

function Agenda({ focus, catalysts, view }: { focus: Date; catalysts: Catalyst[]; view: 'week' | 'day' }) {
  const start = view === 'week' ? startOfWeek(focus) : new Date(focus); const dates = Array.from({ length: view === 'week' ? 7 : 1 }, (_, index) => { const date = new Date(start); date.setDate(start.getDate() + index); return date; });
  return <div className="agenda-view">{dates.map((day) => { const key = dateKey(day); const events = catalysts.filter((item) => item.date === key); return <section key={key}><header><time dateTime={key}>{day.toLocaleDateString(undefined, { weekday: 'short', month: 'short', day: 'numeric' })}</time></header>{events.length ? events.map((item) => <div className={`agenda-event ${category(item)}`} key={item.id}><b>{item.event}</b><span>{item.type} · {item.sensitivity || 'TBD'} sensitivity</span></div>) : <p>No scheduled events.</p>}</section>; })}</div>;
}

export function CatalystsPage({ workspace, onSaved }: { workspace: Workspace; onSaved: () => void }) {
  const [tab, setTab] = useState<Tab>('calendar'); const [view, setView] = useState<View>(workspace.preferences?.calendarView || 'month'); const [focus, setFocus] = useState(new Date());
  const [adding, setAdding] = useState(false); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ event: '', type: 'Employment', date: dateKey(new Date()), sensitivity: 'High', source: '', cluster: '' });
  const title = view === 'month' ? focus.toLocaleDateString(undefined, { month: 'long', year: 'numeric' }) : focus.toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' });
  const upcoming = useMemo(() => workspace.catalysts.filter((item) => item.date && item.date >= dateKey(new Date())).slice(0, 12), [workspace.catalysts]);
  const move = (direction: number) => setFocus((current) => { const next = new Date(current); if (view === 'month') next.setMonth(next.getMonth() + direction); else next.setDate(next.getDate() + direction * (view === 'week' ? 7 : 1)); return next; });
  const save = async () => { setSaving(true); try { await saveCatalystRecord(form); setMessage('Catalyst saved.'); setAdding(false); setForm({ event: '', type: 'Employment', date: dateKey(new Date()), sensitivity: 'High', source: '', cluster: '' }); onSaved(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Catalyst save failed.'); } finally { setSaving(false); } };
  return <div className="page"><PageHeader title="Catalysts" subtitle="Scheduled events and market impact." action={<button className="primary" onClick={() => setAdding(!adding)}><Plus size={17} />Add Catalyst</button>} />
    {adding && <section className="card inline-form"><header><h2>Add Catalyst</h2><p>Record a scheduled event before mapping securities.</p></header><div className="form-grid"><label><span>Event</span><input value={form.event} onChange={(event) => setForm({ ...form, event: event.target.value })} /></label><label><span>Date</span><input type="date" value={form.date} onChange={(event) => setForm({ ...form, date: event.target.value })} /></label><label><span>Category</span><select value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value })}>{['Employment','Inflation','Central bank','Earnings','Policy','Other'].map((item) => <option key={item}>{item}</option>)}</select></label><label><span>Sensitivity</span><select value={form.sensitivity} onChange={(event) => setForm({ ...form, sensitivity: event.target.value })}>{['Low','Medium','High'].map((item) => <option key={item}>{item}</option>)}</select></label><label className="wide"><span>Official source</span><input value={form.source} onChange={(event) => setForm({ ...form, source: event.target.value })} /></label><label className="wide"><span>Cluster</span><input value={form.cluster} placeholder="Optional correlation cluster" onChange={(event) => setForm({ ...form, cluster: event.target.value })} /></label></div><footer><button onClick={() => setAdding(false)}>Cancel</button><button className="primary" disabled={saving || !form.event || !form.date || !workspace.approved} onClick={() => void save()}>{saving ? 'Saving' : 'Save Catalyst'}</button></footer></section>}
    {message && <p className="page-message" role="status">{message}</p>}
    <div className="section-tabs" role="tablist">{(['calendar','radar','mappings'] as Tab[]).map((item) => <button key={item} role="tab" aria-selected={tab === item} className={tab === item ? 'active' : ''} onClick={() => setTab(item)}>{item === 'calendar' ? 'Calendar' : item === 'radar' ? '30-Day Radar' : 'Mappings'}</button>)}</div>
    {tab === 'calendar' && <><div className="calendar-toolbar"><div><button onClick={() => move(-1)} aria-label={`Previous ${view}`}>‹</button><strong>{title}</strong><button onClick={() => move(1)} aria-label={`Next ${view}`}>›</button><button onClick={() => setFocus(new Date())}>Today</button></div><div role="group" aria-label="Calendar view">{(['month','week','day'] as View[]).map((item) => <button key={item} className={view === item ? 'active' : ''} onClick={() => setView(item)}>{item[0].toUpperCase() + item.slice(1)}</button>)}</div></div><section className="card calendar-card">{view === 'month' ? <MonthCalendar focus={focus} catalysts={workspace.catalysts} /> : <Agenda focus={focus} catalysts={workspace.catalysts} view={view} />}</section><div className="calendar-legend"><span className="macro">Macro / Jobs</span><span className="inflation">Inflation</span><span className="policy">Policy</span><span className="earnings">Earnings</span></div></>}
    {tab === 'radar' && (upcoming.length ? <div className="three-grid">{upcoming.map((item) => <SummaryCard key={item.id} title={item.event} subtitle={item.type} status={item.sensitivity || 'TBD'} metric={item.date || 'Date TBD'} meta={item.linkedTickers.join(', ') || 'No mappings'} action={<button className="icon-text" onClick={() => downloadText(`${item.event.replace(/\W+/g, '-')}.md`, catalystMarkdown(item))}><Download size={15} />Export</button>} />)}</div> : <EmptyCard title="No Scheduled Events" subtitle="Research only appears after a date and source are recorded." />)}
    {tab === 'mappings' && (workspace.opportunities.length ? <div className="three-grid">{workspace.opportunities.map((item) => <SummaryCard key={item.id} title={item.ticker} subtitle={item.exposure} status={item.sensitivity || 'TBD'} metric={workspace.catalysts.find((event) => event.id === item.catalystId)?.event || 'Unlinked event'} meta={item.rationale || 'Rationale TBD'} />)}</div> : <EmptyCard title="No Security Mappings" subtitle="Map securities after a catalyst is scheduled." />)}
  </div>;
}
