import { EmptyCard, MetricCard, SummaryCard } from '../components/cards';
import type { Workspace } from '../types/domain';
import { PageHeader } from '../components/layout/AppShell';
import { personalCalibration } from '../data/collaboration';
import { THESIS_HEALTH_LABELS, TRADE_CLASS_LABELS } from '../lib/trade-lifecycle';

export function InsightsPage({ workspace }: { workspace: Workspace }) {
  const reviewed = workspace.journal.filter((item) => item.kind === 'review'); const activeRisk = workspace.positions.filter((item) => item.status === 'active').reduce((sum, item) => sum + (item.maxRisk || 0), 0);
  const strategyCounts = workspace.ideas.reduce<Record<string, number>>((counts, idea) => ({ ...counts, [idea.strategy]: (counts[idea.strategy] || 0) + 1 }), {});
  const catalystCounts = workspace.catalysts.reduce<Record<string, number>>((counts, item) => ({ ...counts, [item.type]: (counts[item.type] || 0) + 1 }), {});
  const calibration = personalCalibration(workspace.profile?.id || '', workspace.forecasts, workspace.debriefs);
  const classified = workspace.positions.filter((item) => item.tradeClass); const averageRisk = workspace.positions.length ? workspace.positions.reduce((sum, item) => sum + (item.maxRisk || 0), 0) / workspace.positions.length : 0;
  const fillComparisons = workspace.positions.filter((item) => item.actualDebit !== undefined && item.entryContext?.candidate?.plannedDebit !== undefined).map((item) => (item.entryContext!.candidate!.plannedDebit! - item.actualDebit!) * 100 * item.contracts);
  const averageFillImprovement = fillComparisons.length ? fillComparisons.reduce((sum, value) => sum + value, 0) / fillComparisons.length : undefined;
  const classCounts = classified.reduce<Record<string, number>>((counts, item) => ({ ...counts, [item.tradeClass!]: (counts[item.tradeClass!] || 0) + 1 }), {});
  return <div className="page" data-tour-id="insights-shell"><PageHeader title="Insights" subtitle="Patterns across your trading history." />
    <section className="metric-grid"><MetricCard title="Ideas" value={workspace.ideas.length} subtitle="All researched setups." /><MetricCard title="Confirmed Trades" value={workspace.positions.length} subtitle="Actual entries only." /><MetricCard title="Reviews" value={reviewed.length} subtitle="Completed trade reviews." /><MetricCard title="Risk in Use" value={`$${activeRisk.toFixed(2)}`} subtitle="Maximum loss across active trades." /></section>
    <div className="dashboard-grid"><section><div className="section-heading"><div><h2>Strategy Mix</h2><p>How research is distributed.</p></div></div>{Object.keys(strategyCounts).length ? <div className="card-list">{Object.entries(strategyCounts).map(([strategy, count]) => <SummaryCard key={strategy} title={strategy} subtitle="Researched ideas" metric={count} />)}</div> : <EmptyCard title="No Strategy Data" subtitle="Insights begin after ideas are saved." />}</section><section><div className="section-heading"><div><h2>Catalyst Mix</h2><p>Scheduled events by category.</p></div></div>{Object.keys(catalystCounts).length ? <div className="card-list">{Object.entries(catalystCounts).map(([type, count]) => <SummaryCard key={type} title={type} subtitle="Scheduled catalysts" metric={count} />)}</div> : <EmptyCard title="No Catalyst Data" subtitle="Add scheduled events to compare categories." />}</section></div>
    <section><div className="section-heading"><div><h2>Trade Lifecycle</h2><p>Entry intention and execution context from confirmed Trades.</p></div></div>{workspace.positions.length ? <><div className="metric-grid"><MetricCard title="Average Defined Risk" value={`$${averageRisk.toFixed(2)}`} subtitle="Maximum loss recorded per confirmed Trade." /><MetricCard title="Average Fill vs Plan" value={averageFillImprovement === undefined ? 'TBD' : `${averageFillImprovement >= 0 ? '+' : '-'}$${Math.abs(averageFillImprovement).toFixed(2)}`} subtitle="Positive means actual debit improved on the Candidate." /><MetricCard title="Invalidated at Exit" value={workspace.positions.filter((item) => item.exit?.thesisHealth === 'invalidated').length} subtitle="User-authored Thesis Health; it never auto-closes a Trade." /></div><div className="three-grid">{Object.entries(classCounts).map(([tradeClass, count]) => <SummaryCard key={tradeClass} title={TRADE_CLASS_LABELS[tradeClass as keyof typeof TRADE_CLASS_LABELS]} subtitle="Confirmed Trades" metric={count} />)}{workspace.positions.filter((item) => item.exit).slice(0, 3).map((item) => <SummaryCard key={item.id} title={item.ticker} subtitle="Thesis at exit" metric={THESIS_HEALTH_LABELS[item.exit!.thesisHealth]} meta={item.exit!.exitReason.replaceAll('_', ' ')} />)}</div></> : <EmptyCard title="No Trade Lifecycle Data" subtitle="Record actual entries and exits to build this history." />}</section>
    <section><div className="section-heading"><div><h2>Personal Forecast Calibration</h2><p>Based only on your locked forecasts with a recorded outcome.</p></div></div>{calibration.count < 3 ? <EmptyCard title="Not Enough Forecasts Yet" subtitle={`${calibration.count} classified forecast${calibration.count === 1 ? '' : 's'}. OJ waits for at least 3 before showing a rate.`} /> : <div className="metric-grid calibration-grid"><MetricCard title="Classified Forecasts" value={calibration.count} subtitle="Locked before their event cutoff." /><MetricCard title="Direction Accuracy" value={`${Math.round((calibration.directionAccuracy || 0) * 100)}%`} subtitle="Exact bullish, bearish, neutral, or mixed match." /><MetricCard title="Average Confidence" value={`${Math.round(calibration.averageConfidence || 0)}%`} subtitle="Your stated confidence, not a prediction score." /><MetricCard title="Magnitude Error" value={calibration.averageMagnitudeError === undefined ? 'N/A' : calibration.averageMagnitudeError.toFixed(2)} subtitle="Mean absolute error where both values exist." /></div>}</section>
    <section className="card interpretation"><h2>Interpretation</h2><p>{workspace.positions.length < 5 ? 'More confirmed trades are needed before outcome rates are meaningful.' : 'Review strategy and catalyst results together before changing risk rules.'}</p></section>
  </div>;
}
