import { ArrowRight, Plus, Users } from 'lucide-react';
import { MetricCard, SummaryCard, EmptyCard } from '../components/cards';
import { navigate, navigateToCatalyst } from '../config/navigation';
import type { Workspace } from '../types/domain';
import { PageHeader } from '../components/layout/AppShell';
import { CatalystSourceLink } from '../components/CatalystSourceLink';
import { openRiskSummary } from '../lib/trade-lifecycle';

export function OverviewPage({ workspace, onBuildIdea }: { workspace: Workspace; onBuildIdea: () => void }) {
  const active = workspace.positions.filter((item) => item.status === 'active'); const risk = openRiskSummary(workspace.positions, workspace.policy?.maximumOpenRisk);
  const upcoming = workspace.catalysts.filter((item) => item.date && item.date >= new Date().toISOString().slice(0, 10)).slice(0, 4);
  const drafts = workspace.ideas.filter((item) => ['draft','watchlist','ready'].includes(item.status)).slice(0, 3);
  return <div className="page" data-tour-id="overview-shell"><PageHeader title="Overview" subtitle="Risk, trades, and upcoming events." action={<button className="primary" onClick={onBuildIdea}><Plus size={17} />Build Idea</button>} />
    <section className="metric-grid" aria-label="Account summary" data-tour-id="overview-risk"><MetricCard title="Open Options Max Loss" value={`$${risk.used.toFixed(2)}`} subtitle="Actual defined-risk loss across open Trades." /><MetricCard title="Remaining OJ Capacity" value={risk.remaining === undefined ? 'TBD' : `${risk.remaining < 0 ? '-' : ''}$${Math.abs(risk.remaining).toFixed(2)}`} subtitle="OJ risk-policy capacity—not brokerage buying power." /><MetricCard title="Active Trades" value={active.length} subtitle="Confirmed open positions." /><MetricCard title="Pending Debriefs" value={workspace.pendingReviews} subtitle="Closed Trades awaiting reflection." /></section>
    <div className="dashboard-grid"><section><div className="section-heading"><div><h2>Active Trades</h2><p>Confirmed positions requiring attention.</p></div><button className="text-button" onClick={() => navigate('/trades')}>View Trades <ArrowRight size={15} /></button></div>{active.length ? <div className="card-list">{active.slice(0, 3).map((trade) => <SummaryCard key={trade.id} title={trade.ticker} subtitle={trade.strategy} status="Active" metric={trade.maxRisk === undefined ? 'Risk TBD' : `$${trade.maxRisk.toFixed(2)} risk`} meta={`${trade.contracts} contract${trade.contracts === 1 ? '' : 's'} · Expires ${trade.expiration || 'TBD'}`} />)}</div> : <EmptyCard title="No Active Trades" subtitle="Confirmed entries will appear here." />}</section>
      <section><div className="section-heading"><div><h2>Upcoming Catalysts</h2><p>The next scheduled events.</p></div><button className="text-button" onClick={() => navigate('/catalysts')}>View Catalysts <ArrowRight size={15} /></button></div>{upcoming.length ? <div className="card-list">{upcoming.map((item) => <SummaryCard key={item.id} title={<CatalystSourceLink source={item.source}>{item.event}</CatalystSourceLink>} subtitle={item.type} status={item.sensitivity || 'TBD'} metric={item.date} meta={item.linkedTickers.join(', ') || 'No mapping'} action={<button className="text-button" onClick={() => navigateToCatalyst(item.id)}>War Room <ArrowRight size={14} /></button>} />)}</div> : <EmptyCard title="No Upcoming Events" subtitle="Add a scheduled catalyst to begin research." />}</section>
    </div>
    {workspace.researchWorkspace && <section className="card workspace-overview-card"><div><Users size={20} /><div><span className="eyebrow">Research workspace</span><h2>{workspace.researchWorkspace.name}</h2><p>{workspace.workspaceMembers.length} member{workspace.workspaceMembers.length === 1 ? '' : 's'} · {workspace.missions.filter((mission) => mission.status === 'active').length} active mission{workspace.missions.filter((mission) => mission.status === 'active').length === 1 ? '' : 's'} · {workspace.researchQuestions.filter((question) => question.status === 'open').length} open question{workspace.researchQuestions.filter((question) => question.status === 'open').length === 1 ? '' : 's'}</p></div></div><button className="text-button" onClick={() => navigate('/workspace')}>View Workspace <ArrowRight size={15} /></button></section>}
    <section><div className="section-heading"><div><h2>Draft Ideas</h2><p>Research that may need a decision.</p></div><button className="text-button" onClick={() => navigate('/ideas')}>View Ideas <ArrowRight size={15} /></button></div>{drafts.length ? <div className="three-grid">{drafts.map((idea) => <SummaryCard key={idea.id} title={idea.ticker} subtitle={idea.strategy} status={idea.status} metric={idea.risk === undefined ? 'Risk TBD' : `$${idea.risk.toFixed(2)} risk`} meta={`Updated ${new Date(idea.updatedAt).toLocaleDateString()}`} />)}</div> : <EmptyCard title="No Draft Ideas" subtitle="Build an idea from a ticker or catalyst." action={<button onClick={onBuildIdea}>Build Idea</button>} />}</section>
  </div>;
}
