import { useEffect, useState } from 'react';
import { Compass, Download, FlaskConical, KeyRound, LogOut, MailPlus, Save, UserMinus, Users } from 'lucide-react';
import { saveAccountPolicy } from '../data/actions';
import { savePreferences } from '../data/workspace';
import { downloadJournal } from '../features/export/markdown';
import type { Workspace } from '../types/domain';
import { PageHeader } from '../components/layout/AppShell';
import { inviteAccount, setAccountPassword, updateAccountProfile } from '../lib/auth';
import { supabase } from '../lib/supabase';
import { acceptWorkspaceInvite, leaveResearchWorkspace, removeWorkspaceMember, renameResearchWorkspace } from '../data/collaboration-actions';
import { MemberBadge } from '../components/MemberBadge';
import { primaryNavigation, replaceMobileNavigationShortcut, type PrimaryPath } from '../config/navigation';
import type { AppPreferences } from '../types/domain';
import { productTourActionLabel, readProductTourState, type ProductTourState } from '../features/tour/product-tour';
import { guidedTutorialActionLabel, readGuidedTutorialState, type GuidedTutorialState } from '../features/tour/guided-tutorial';

export function SettingsPage({ workspace, onSaved, tourState, guidedState, onStartTour, onStartGuided }: { workspace: Workspace; onSaved: () => void; tourState?: ProductTourState; guidedState?: GuidedTutorialState; onStartTour?: (step: number) => void; onStartGuided?: (restart: boolean) => void }) {
  const [message, setMessage] = useState('');
  const [account, setAccount] = useState({ displayName: workspace.profile?.displayName || '', initials: workspace.profile?.initials || '' });
  const [password, setPassword] = useState({ current: '', next: '', confirmation: '' }); const [inviteEmail, setInviteEmail] = useState(''); const [busy, setBusy] = useState('');
  const [workspaceName, setWorkspaceName] = useState(workspace.researchWorkspace?.name || '');
  const [policy, setPolicy] = useState({ total: '', maximum: '', fixed: '', strategies: 'bull-call-spread, bear-put-spread', effectiveDate: new Date().toISOString().slice(0, 10) });
  const [preferences, setPreferences] = useState<Omit<AppPreferences, 'revision'>>({ theme: workspace.preferences?.theme || 'system', calendarView: workspace.preferences?.calendarView || 'month', compactCards: workspace.preferences?.compactCards || false, mobileNavigation: workspace.preferences?.mobileNavigation || ['/', '/catalysts', '/ideas', '/trades'], data: workspace.preferences?.data || {} });
  useEffect(() => { if (workspace.policy) setPolicy({ total: String(workspace.policy.totalCapital), maximum: String(workspace.policy.maximumOpenRisk), fixed: workspace.policy.fixedPerTradeLimit === undefined ? '' : String(workspace.policy.fixedPerTradeLimit), strategies: workspace.policy.strategies.join(', '), effectiveDate: workspace.policy.effectiveDate }); }, [workspace.policy]);
  useEffect(() => { if (workspace.profile) setAccount({ displayName: workspace.profile.displayName, initials: workspace.profile.initials }); }, [workspace.profile]);
  useEffect(() => { setWorkspaceName(workspace.researchWorkspace?.name || ''); }, [workspace.researchWorkspace?.name]);
  const savePolicy = async () => { try { const total = Number(policy.total); const maximum = Number(policy.maximum); if (!(total > 0) || !(maximum > 0) || maximum > total) throw new Error('Enter a valid total and maximum open risk.'); await saveAccountPolicy({ totalCapital: total, maximumOpenRisk: maximum, fixedPerTradeLimit: policy.fixed ? Number(policy.fixed) : undefined, strategies: policy.strategies.split(',').map((item) => item.trim()).filter(Boolean), effectiveDate: policy.effectiveDate, version: (workspace.policy?.version || 0) + 1 }, Boolean(workspace.policy)); setMessage('Risk policy saved.'); onSaved(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Policy save failed.'); } };
  const savePrefs = async () => { try { if (preferences.mobileNavigation.length !== 4) throw new Error('Choose exactly four mobile navigation shortcuts.'); const latestTour = workspace.preferences?.data?.productTour; const latestGuided = workspace.preferences?.data?.guidedWalkthrough; await savePreferences({ ...preferences, data: { ...preferences.data, ...(latestTour ? { productTour: latestTour } : {}), ...(latestGuided ? { guidedWalkthrough: latestGuided } : {}) } }, workspace.preferences?.revision); setMessage('Preferences saved.'); onSaved(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Preference save failed.'); } };
  const setMobileShortcut = (index: number, path: PrimaryPath) => setPreferences((current) => ({ ...current, mobileNavigation: replaceMobileNavigationShortcut(current.mobileNavigation, index, path) }));
  const saveAccount = async () => { setBusy('account'); try { await updateAccountProfile(account.displayName, account.initials); setMessage('Account profile saved.'); onSaved(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Profile save failed.'); } finally { setBusy(''); } };
  const changePassword = async () => { setBusy('password'); try { await setAccountPassword(password.next, password.confirmation, password.current); setPassword({ current: '', next: '', confirmation: '' }); setMessage('Password updated.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Password update failed.'); } finally { setBusy(''); } };
  const currentMembership = workspace.workspaceMembers.find((member) => member.userId === workspace.profile?.id);
  const workspaceOwner = currentMembership?.workspaceRole === 'owner';
  const sendInvite = async () => { setBusy('invite'); try { if (!workspace.researchWorkspace) throw new Error('Workspace is not ready.'); await inviteAccount(inviteEmail, workspace.researchWorkspace.id); setInviteEmail(''); setMessage('Workspace invitation sent.'); onSaved(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Invitation failed.'); } finally { setBusy(''); } };
  const saveWorkspaceName = async () => { if (!workspace.researchWorkspace) return; setBusy('workspace'); try { await renameResearchWorkspace(workspace.researchWorkspace.id, workspaceName); setMessage('Workspace name saved.'); onSaved(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Workspace could not be renamed.'); } finally { setBusy(''); } };
  const acceptInvite = async (inviteId: string) => { setBusy(inviteId); try { await acceptWorkspaceInvite(inviteId); setMessage('Workspace invitation accepted.'); onSaved(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Invitation could not be accepted.'); } finally { setBusy(''); } };
  const removeMember = async (userId: string, name: string) => { if (!workspace.researchWorkspace || !window.confirm(`Remove ${name} from this research workspace? Their private OJ records are unaffected.`)) return; setBusy(userId); try { await removeWorkspaceMember(workspace.researchWorkspace.id, userId); setMessage(`${name} removed from the workspace.`); onSaved(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Member could not be removed.'); } finally { setBusy(''); } };
  const leaveWorkspace = async () => { if (!workspace.researchWorkspace || !window.confirm('Leave this research workspace? Your private OJ records remain yours.')) return; setBusy('leave'); try { await leaveResearchWorkspace(workspace.researchWorkspace.id); setMessage('You left the workspace.'); onSaved(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Workspace could not be left.'); } finally { setBusy(''); } };
  const currentTour = tourState || readProductTourState(workspace.preferences?.data);
  const currentGuided = guidedState || readGuidedTutorialState(workspace.preferences?.data);
  return <div className="page"><PageHeader title="Settings" subtitle="Account, risk, and export controls." />
    {message && <p className="page-message" role="status" aria-live="polite">{message}</p>}<div className="settings-grid">
      {workspace.profile && <section className="card inline-form settings-account"><header><h2>Account</h2><p>Manage your sign-in and profile.</p></header><div className="account-summary"><span className="account-initials" aria-hidden="true">{workspace.profile.initials}</span><div><b>{workspace.profile.displayName}</b><span>{workspace.profile.email}</span><span>{workspace.profile.role === 'owner' ? 'Owner' : 'Member'}</span></div></div><div className="form-grid"><label><span>Display Name</span><input autoComplete="name" value={account.displayName} onChange={(event) => setAccount({ ...account, displayName: event.target.value })} /></label><label><span>Initials</span><input autoCapitalize="characters" maxLength={4} value={account.initials} onChange={(event) => setAccount({ ...account, initials: event.target.value.toUpperCase() })} /></label></div><footer><button className="primary" onClick={() => void saveAccount()} disabled={busy === 'account'}><Save size={16} />{busy === 'account' ? 'Saving' : 'Save Account'}</button></footer></section>}
      <section className="card inline-form"><header><h2>Security</h2><p>Password and active sessions.</p></header><div className="form-grid single"><label><span>Current Password</span><input type="password" autoComplete="current-password" value={password.current} onChange={(event) => setPassword({ ...password, current: event.target.value })} /></label><label><span>New Password</span><input type="password" autoComplete="new-password" value={password.next} onChange={(event) => setPassword({ ...password, next: event.target.value })} /></label><label><span>Confirm Password</span><input type="password" autoComplete="new-password" value={password.confirmation} onChange={(event) => setPassword({ ...password, confirmation: event.target.value })} /></label></div><div className="security-actions"><button className="primary" onClick={() => void changePassword()} disabled={busy === 'password' || !password.current || !password.next}><KeyRound size={16} />{busy === 'password' ? 'Updating' : 'Change Password'}</button><button onClick={() => void supabase?.auth.signOut({ scope: 'local' })}><LogOut size={16} />Sign Out This Device</button><button onClick={() => void supabase?.auth.signOut({ scope: 'global' })}><LogOut size={16} />Sign Out Everywhere</button></div></section>
      {workspace.pendingWorkspaceInvites.length > 0 && <section className="card inline-form"><header><h2>Workspace Invitations</h2><p>Join a shared research desk. Your money, trades, ideas, forecasts, and journal remain private.</p></header><div className="workspace-invites">{workspace.pendingWorkspaceInvites.map((invite) => <div key={invite.id}><div><b>{invite.workspaceName}</b><span>Invited by {invite.invitedByName}</span></div><button className="primary" disabled={busy === invite.id} onClick={() => void acceptInvite(invite.id)}>{busy === invite.id ? 'Joining' : 'Accept'}</button></div>)}</div></section>}
      {workspace.researchWorkspace && <section className="card inline-form workspace-access"><header><h2>Workspace Access</h2><p>Manage shared research separately from OJ account roles.</p></header>{workspaceOwner && <div className="form-grid single"><label><span>Workspace name</span><input value={workspaceName} onChange={(event) => setWorkspaceName(event.target.value)} /></label><button className="secondary-save" disabled={!workspaceName.trim() || busy === 'workspace'} onClick={() => void saveWorkspaceName()}><Save size={15} />Save Name</button></div>}<div className="member-list">{workspace.workspaceMembers.map((member) => <div key={member.userId}><MemberBadge initials={member.initials} name={member.displayName} /><span>{member.workspaceRole === 'owner' ? 'Workspace owner' : 'Workspace member'}</span>{workspaceOwner && member.workspaceRole !== 'owner' && <button className="icon-button" aria-label={`Remove ${member.displayName}`} disabled={busy === member.userId} onClick={() => void removeMember(member.userId, member.displayName)}><UserMinus size={16} /></button>}</div>)}</div>{workspaceOwner && <div className="form-grid single workspace-invite-form"><label><span>Invite by email</span><input type="email" inputMode="email" autoCapitalize="none" autoCorrect="off" autoComplete="email" value={inviteEmail} onChange={(event) => setInviteEmail(event.target.value)} /></label><button className="primary" onClick={() => void sendInvite()} disabled={busy === 'invite' || !inviteEmail.includes('@')}><MailPlus size={16} />{busy === 'invite' ? 'Sending' : 'Send Workspace Invite'}</button></div>}{!workspaceOwner && <footer><button className="subtle-danger" disabled={busy === 'leave'} onClick={() => void leaveWorkspace()}><Users size={16} />{busy === 'leave' ? 'Leaving' : 'Leave Workspace'}</button></footer>}</section>}
      <section className="card inline-form"><header><h2>Risk Policy</h2><p>Set an OJ research rule deliberately. This is not brokerage buying power, cash, margin, or an automatic sizing target.</p></header><div className="form-grid"><label><span>Total account capital</span><input inputMode="decimal" value={policy.total} onChange={(event) => setPolicy({ ...policy, total: event.target.value })} /></label><label><span>Open-options max-loss ceiling</span><input inputMode="decimal" value={policy.maximum} onChange={(event) => setPolicy({ ...policy, maximum: event.target.value })} /></label><label><span>Fixed per-trade limit</span><input inputMode="decimal" placeholder="Optional" value={policy.fixed} onChange={(event) => setPolicy({ ...policy, fixed: event.target.value })} /></label><label><span>Effective date</span><input type="date" value={policy.effectiveDate} onChange={(event) => setPolicy({ ...policy, effectiveDate: event.target.value })} /></label><label className="wide"><span>Defined-risk strategies</span><input value={policy.strategies} onChange={(event) => setPolicy({ ...policy, strategies: event.target.value })} /></label></div><footer><button className="primary" onClick={() => void savePolicy()} disabled={!workspace.approved}><Save size={16} />Save Policy</button></footer></section>
      <section className="card inline-form"><header><h2>Preferences</h2><p>Control display defaults across devices.</p></header><div className="form-grid single"><label><span>Theme</span><select value={preferences.theme} onChange={(event) => setPreferences({ ...preferences, theme: event.target.value as typeof preferences.theme })}><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></label><label><span>Calendar view</span><select value={preferences.calendarView} onChange={(event) => setPreferences({ ...preferences, calendarView: event.target.value as typeof preferences.calendarView })}><option value="month">Month</option><option value="week">Week</option><option value="day">Day</option></select></label><label className="confirm-row"><input type="checkbox" checked={preferences.compactCards} onChange={(event) => setPreferences({ ...preferences, compactCards: event.target.checked })} /><span>Use compact summary cards</span></label><div className="mobile-nav-preference"><header><div><b>Mobile navigation</b><span>Choose and order four shortcuts. Everything else stays available in More.</span></div><strong>4 + More</strong></header><div className="mobile-nav-slots">{preferences.mobileNavigation.map((path, index) => <label key={index}><span>Shortcut {index + 1}</span><select value={path} onChange={(event) => setMobileShortcut(index, event.target.value as PrimaryPath)}>{primaryNavigation.map((item) => <option key={item.path} value={item.path}>{item.label}</option>)}</select></label>)}</div><div className="mobile-nav-preview" aria-label="Mobile navigation preview">{preferences.mobileNavigation.map((path) => { const item = primaryNavigation.find((candidate) => candidate.path === path)!; const Icon = item.icon; return <span key={item.path}><Icon size={16} />{item.label}</span>; })}<span><span className="preview-menu-icon" aria-hidden="true">☰</span>More</span></div></div></div><footer><button className="primary" onClick={() => void savePrefs()} disabled={!workspace.approved || preferences.mobileNavigation.length !== 4}><Save size={16} />Save Preferences</button></footer></section>
      <section className="card export-card guidance-card" data-tour-id="tour-guidance"><h2>Product Tour</h2><p>Review the workflow without changing real research, Trades, provider data, or brokerage activity.</p><div className="guidance-option"><div><b>Quick Tour</b><span>See how OJ fits together.</span><span className="tour-guidance-status" data-status={currentTour.status}>{currentTour.status.replace('_', ' ')}</span></div><button onClick={() => onStartTour?.(currentTour.status === 'in_progress' ? currentTour.step : 0)}><Compass size={16} />{productTourActionLabel(currentTour)}</button></div><div className="guidance-option"><div><b>Guided Walkthrough</b><span>Practice with a disposable synthetic example.</span><span className="tour-guidance-status" data-status={currentGuided.status}>{currentGuided.status.replace('_', ' ')}</span></div><div className="action-row"><button onClick={() => onStartGuided?.(false)}><FlaskConical size={16} />{guidedTutorialActionLabel(currentGuided)}</button>{['paused', 'in_progress', 'completed'].includes(currentGuided.status) && <button onClick={() => onStartGuided?.(true)}>Restart</button>}</div></div></section>
      <section className="card export-card"><h2>Markdown Export</h2><p>Download an optional Obsidian-friendly mirror. OJ continues to use Supabase as its canonical store.</p><button onClick={() => downloadJournal(workspace)}><Download size={16} />Export Journal</button></section><section className="card export-card"><h2>Privacy</h2><p>OJ stores private records behind owner-scoped RLS. The public site contains code and synthetic examples only. Brokerage credentials are never used.</p></section></div>
  </div>;
}
