import { useEffect, useState } from 'react';
import { Download, KeyRound, LogOut, MailPlus, Save } from 'lucide-react';
import { saveAccountPolicy } from '../data/actions';
import { savePreferences } from '../data/workspace';
import { downloadJournal } from '../features/export/markdown';
import type { Workspace } from '../types/domain';
import { PageHeader } from '../components/layout/AppShell';
import { inviteAccount, setAccountPassword, updateAccountProfile } from '../lib/auth';
import { supabase } from '../lib/supabase';

export function SettingsPage({ workspace, onSaved }: { workspace: Workspace; onSaved: () => void }) {
  const [message, setMessage] = useState('');
  const [account, setAccount] = useState({ displayName: workspace.profile?.displayName || '', initials: workspace.profile?.initials || '' });
  const [password, setPassword] = useState({ current: '', next: '', confirmation: '' }); const [inviteEmail, setInviteEmail] = useState(''); const [busy, setBusy] = useState('');
  const [policy, setPolicy] = useState({ total: '', maximum: '', fixed: '', strategies: 'bull-call-spread, bear-put-spread', effectiveDate: new Date().toISOString().slice(0, 10) });
  const [preferences, setPreferences] = useState({ theme: workspace.preferences?.theme || 'system', calendarView: workspace.preferences?.calendarView || 'month', compactCards: workspace.preferences?.compactCards || false });
  useEffect(() => { if (workspace.policy) setPolicy({ total: String(workspace.policy.totalCapital), maximum: String(workspace.policy.maximumOpenRisk), fixed: workspace.policy.fixedPerTradeLimit === undefined ? '' : String(workspace.policy.fixedPerTradeLimit), strategies: workspace.policy.strategies.join(', '), effectiveDate: workspace.policy.effectiveDate }); }, [workspace.policy]);
  useEffect(() => { if (workspace.profile) setAccount({ displayName: workspace.profile.displayName, initials: workspace.profile.initials }); }, [workspace.profile]);
  const savePolicy = async () => { try { const total = Number(policy.total); const maximum = Number(policy.maximum); if (!(total > 0) || !(maximum > 0) || maximum > total) throw new Error('Enter a valid total and maximum open risk.'); await saveAccountPolicy({ totalCapital: total, maximumOpenRisk: maximum, fixedPerTradeLimit: policy.fixed ? Number(policy.fixed) : undefined, strategies: policy.strategies.split(',').map((item) => item.trim()).filter(Boolean), effectiveDate: policy.effectiveDate, version: (workspace.policy?.version || 0) + 1 }, Boolean(workspace.policy)); setMessage('Risk policy saved.'); onSaved(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Policy save failed.'); } };
  const savePrefs = async () => { try { await savePreferences(preferences, workspace.preferences?.revision); setMessage('Preferences saved.'); onSaved(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Preference save failed.'); } };
  const saveAccount = async () => { setBusy('account'); try { await updateAccountProfile(account.displayName, account.initials); setMessage('Account profile saved.'); onSaved(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Profile save failed.'); } finally { setBusy(''); } };
  const changePassword = async () => { setBusy('password'); try { await setAccountPassword(password.next, password.confirmation, password.current); setPassword({ current: '', next: '', confirmation: '' }); setMessage('Password updated.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Password update failed.'); } finally { setBusy(''); } };
  const sendInvite = async () => { setBusy('invite'); try { await inviteAccount(inviteEmail); setInviteEmail(''); setMessage('Invitation sent.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Invitation failed.'); } finally { setBusy(''); } };
  return <div className="page"><PageHeader title="Settings" subtitle="Account, risk, and export controls." />
    {message && <p className="page-message" role="status" aria-live="polite">{message}</p>}<div className="settings-grid">
      {workspace.profile && <section className="card inline-form settings-account"><header><h2>Account</h2><p>Manage your sign-in and profile.</p></header><div className="account-summary"><span className="account-initials" aria-hidden="true">{workspace.profile.initials}</span><div><b>{workspace.profile.displayName}</b><span>{workspace.profile.email}</span><span>{workspace.profile.role === 'owner' ? 'Owner' : 'Member'}</span></div></div><div className="form-grid"><label><span>Display Name</span><input autoComplete="name" value={account.displayName} onChange={(event) => setAccount({ ...account, displayName: event.target.value })} /></label><label><span>Initials</span><input autoCapitalize="characters" maxLength={4} value={account.initials} onChange={(event) => setAccount({ ...account, initials: event.target.value.toUpperCase() })} /></label></div><footer><button className="primary" onClick={() => void saveAccount()} disabled={busy === 'account'}><Save size={16} />{busy === 'account' ? 'Saving' : 'Save Account'}</button></footer></section>}
      <section className="card inline-form"><header><h2>Security</h2><p>Password and active sessions.</p></header><div className="form-grid single"><label><span>Current Password</span><input type="password" autoComplete="current-password" value={password.current} onChange={(event) => setPassword({ ...password, current: event.target.value })} /></label><label><span>New Password</span><input type="password" autoComplete="new-password" value={password.next} onChange={(event) => setPassword({ ...password, next: event.target.value })} /></label><label><span>Confirm Password</span><input type="password" autoComplete="new-password" value={password.confirmation} onChange={(event) => setPassword({ ...password, confirmation: event.target.value })} /></label></div><div className="security-actions"><button className="primary" onClick={() => void changePassword()} disabled={busy === 'password' || !password.current || !password.next}><KeyRound size={16} />{busy === 'password' ? 'Updating' : 'Change Password'}</button><button onClick={() => void supabase?.auth.signOut({ scope: 'local' })}><LogOut size={16} />Sign Out This Device</button><button onClick={() => void supabase?.auth.signOut({ scope: 'global' })}><LogOut size={16} />Sign Out Everywhere</button></div></section>
      {workspace.profile?.role === 'owner' && <section className="card inline-form"><header><h2>Access</h2><p>Invite a future OJ member.</p></header><div className="form-grid single"><label><span>Email</span><input type="email" inputMode="email" autoCapitalize="none" autoCorrect="off" autoComplete="email" value={inviteEmail} onChange={(event) => setInviteEmail(event.target.value)} /></label></div><footer><button className="primary" onClick={() => void sendInvite()} disabled={busy === 'invite' || !inviteEmail.includes('@')}><MailPlus size={16} />{busy === 'invite' ? 'Sending' : 'Send Invite'}</button></footer></section>}
      <section className="card inline-form"><header><h2>Risk Policy</h2><p>Set portfolio capacity without forcing full deployment.</p></header><div className="form-grid"><label><span>Total account capital</span><input inputMode="decimal" value={policy.total} onChange={(event) => setPolicy({ ...policy, total: event.target.value })} /></label><label><span>Maximum open risk</span><input inputMode="decimal" value={policy.maximum} onChange={(event) => setPolicy({ ...policy, maximum: event.target.value })} /></label><label><span>Fixed per-trade limit</span><input inputMode="decimal" placeholder="Optional" value={policy.fixed} onChange={(event) => setPolicy({ ...policy, fixed: event.target.value })} /></label><label><span>Effective date</span><input type="date" value={policy.effectiveDate} onChange={(event) => setPolicy({ ...policy, effectiveDate: event.target.value })} /></label><label className="wide"><span>Defined-risk strategies</span><input value={policy.strategies} onChange={(event) => setPolicy({ ...policy, strategies: event.target.value })} /></label></div><footer><button className="primary" onClick={() => void savePolicy()} disabled={!workspace.approved}><Save size={16} />Save Policy</button></footer></section>
      <section className="card inline-form"><header><h2>Preferences</h2><p>Control display defaults across devices.</p></header><div className="form-grid single"><label><span>Theme</span><select value={preferences.theme} onChange={(event) => setPreferences({ ...preferences, theme: event.target.value as typeof preferences.theme })}><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></label><label><span>Calendar view</span><select value={preferences.calendarView} onChange={(event) => setPreferences({ ...preferences, calendarView: event.target.value as typeof preferences.calendarView })}><option value="month">Month</option><option value="week">Week</option><option value="day">Day</option></select></label><label className="confirm-row"><input type="checkbox" checked={preferences.compactCards} onChange={(event) => setPreferences({ ...preferences, compactCards: event.target.checked })} /><span>Use compact summary cards</span></label></div><footer><button className="primary" onClick={() => void savePrefs()} disabled={!workspace.approved}><Save size={16} />Save Preferences</button></footer></section>
      <section className="card export-card"><h2>Markdown Export</h2><p>Download an optional Obsidian-friendly mirror. OJ continues to use Supabase as its canonical store.</p><button onClick={() => downloadJournal(workspace)}><Download size={16} />Export Journal</button></section><section className="card export-card"><h2>Privacy</h2><p>OJ stores private records behind owner-scoped RLS. The public site contains code and synthetic examples only. Brokerage credentials are never used.</p></section></div>
  </div>;
}
