import { useState } from 'react';
import { Plus } from 'lucide-react';
import { EmptyCard, SummaryCard } from '../components/cards';
import { recordEntry } from '../data/actions';
import type { Workspace } from '../types/domain';
import { PageHeader } from '../components/layout/AppShell';

export function TradesPage({ workspace, onSaved }: { workspace: Workspace; onSaved: () => void }) {
  const [tab, setTab] = useState<'active' | 'closed'>('active'); const [entry, setEntry] = useState(false); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ ideaId: '', contracts: '1', openedAt: new Date().toISOString().slice(0, 16), maxRisk: '', debit: '', notes: '', confirmed: false });
  const positions = workspace.positions.filter((item) => item.status === tab);
  const submit = async () => { setSaving(true); try { await recordEntry({ ideaId: form.ideaId, contracts: Number(form.contracts), openedAt: form.openedAt, maxRisk: Number(form.maxRisk), debit: form.debit ? Number(form.debit) : undefined, notes: form.notes, confirmed: form.confirmed }); setMessage('Entry recorded.'); setEntry(false); onSaved(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Entry failed.'); } finally { setSaving(false); } };
  return <div className="page"><PageHeader title="Trades" subtitle="Track positions and execution." action={<button className="primary" onClick={() => setEntry(!entry)}><Plus size={17} />Record Entry</button>} />
    <div className="section-tabs" role="tablist"><button role="tab" aria-selected={tab === 'active'} className={tab === 'active' ? 'active' : ''} onClick={() => setTab('active')}>Active</button><button role="tab" aria-selected={tab === 'closed'} className={tab === 'closed' ? 'active' : ''} onClick={() => setTab('closed')}>Closed</button></div>
    {entry && <section className="card inline-form"><header><h2>Record Entry</h2><p>Use only after an actual fill is confirmed.</p></header><div className="form-grid"><label><span>Trade idea</span><select value={form.ideaId} onChange={(event) => setForm({ ...form, ideaId: event.target.value })}><option value="">Select a ready idea</option>{workspace.ideas.filter((idea) => !workspace.positions.some((position) => position.ideaId === idea.id)).map((idea) => <option key={idea.id} value={idea.id}>{idea.ticker} · {idea.strategy}</option>)}</select></label><label><span>Contracts</span><input inputMode="numeric" value={form.contracts} onChange={(event) => setForm({ ...form, contracts: event.target.value })} /></label><label><span>Filled at</span><input type="datetime-local" value={form.openedAt} onChange={(event) => setForm({ ...form, openedAt: event.target.value })} /></label><label><span>Maximum risk</span><input inputMode="decimal" value={form.maxRisk} onChange={(event) => setForm({ ...form, maxRisk: event.target.value })} /></label><label><span>Net debit</span><input inputMode="decimal" value={form.debit} onChange={(event) => setForm({ ...form, debit: event.target.value })} /></label><label className="wide"><span>Notes</span><textarea value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} /></label></div><label className="confirm-row"><input type="checkbox" checked={form.confirmed} onChange={(event) => setForm({ ...form, confirmed: event.target.checked })} /><span>I confirm this is an actual fill. OJ will create an active position.</span></label><footer><button onClick={() => setEntry(false)}>Cancel</button><button className="primary" disabled={saving || !form.ideaId || !form.maxRisk || !form.confirmed} onClick={() => void submit()}>{saving ? 'Saving' : 'Record Entry'}</button></footer></section>}
    {message && <p className="page-message" role="status">{message}</p>}{positions.length ? <div className="three-grid">{positions.map((item) => <SummaryCard key={item.id} title={item.ticker} subtitle={item.strategy} status={item.status} metric={item.maxRisk === undefined ? 'Risk TBD' : `$${item.maxRisk.toFixed(2)} risk`} meta={`${item.contracts} contract${item.contracts === 1 ? '' : 's'} · ${new Date(item.openedAt).toLocaleDateString()}`} />)}</div> : <EmptyCard title={tab === 'active' ? 'No Active Trades' : 'No Closed Trades'} subtitle={tab === 'active' ? 'Watchlist research remains in Ideas. Only confirmed entries appear here.' : 'Closed positions will remain available for review.'} />}
  </div>;
}
