import { ArrowRight, CheckCircle2, CircleHelp, FlaskConical, Share2 } from 'lucide-react';
import { EmptyCard, MetricCard } from '../components/cards';
import { PageHeader } from '../components/layout/AppShell';
import { MemberBadge } from '../components/MemberBadge';
import { navigate, navigateToCatalyst } from '../config/navigation';
import { memberLabel } from '../data/collaboration';
import type { Workspace } from '../types/domain';

export function WorkspacePage({ workspace }: { workspace: Workspace }) {
  const research = workspace.researchWorkspace;
  const activeMissions = workspace.missions.filter((mission) => mission.status === 'active');
  const openQuestions = workspace.researchQuestions.filter((question) => question.status === 'open');
  const pendingDebriefs = workspace.missions.filter((mission) => mission.status === 'completed' && !workspace.debriefs.some((debrief) => debrief.missionId === mission.id && debrief.authorId === workspace.profile?.id));
  if (!research) return <div className="page"><PageHeader title="Workspace" subtitle="Shared research without shared accounts or trades." /><EmptyCard title="Your Solo Workspace Is Being Prepared" subtitle="Your private ideas, trades, account values, forecasts, and journal remain private. Refresh after the workspace migration is deployed." /></div>;
  return <div className="page workspace-page"><PageHeader title={research.name} subtitle="Shared facts and research coordination. Money, trades, private ideas, forecasts, and journal entries stay personal." />
    <section className="metric-grid" aria-label="Workspace summary"><MetricCard title="Members" value={workspace.workspaceMembers.length} subtitle="Initials identify active collaborators." /><MetricCard title="Active Missions" value={activeMissions.length} subtitle="Catalyst research in progress." /><MetricCard title="Open Questions" value={openQuestions.length} subtitle="Questions still needing evidence." /><MetricCard title="Pending Debriefs" value={pendingDebriefs.length} subtitle="Completed missions awaiting your review." /></section>
    <section className="card workspace-overview-card"><div><Share2 size={20} /><div><span className="eyebrow">Shared theses</span><h2>{workspace.sharedTheses.length} visible in this workspace</h2><p>Manage your own shares without changing the underlying private Ideas.</p></div></div><button className="text-button" onClick={() => navigate('/ideas')}>Manage Shared Theses <ArrowRight size={15} /></button></section>
    <div className="dashboard-grid"><section><div className="section-heading"><div><h2>Research Missions</h2><p>Work stays optional and a No Trade result is valid.</p></div><button className="text-button" onClick={() => navigate('/catalysts')}>Open Catalysts <ArrowRight size={15} /></button></div>{activeMissions.length ? <div className="card-list">{activeMissions.map((mission) => { const catalyst = workspace.catalysts.find((item) => item.id === mission.catalystId); const checkpoints = workspace.missionCheckpoints.filter((item) => item.missionId === mission.id); const complete = checkpoints.filter((item) => item.status === 'completed').length; return <article className="card workspace-mission" key={mission.id}><div><FlaskConical size={18} /><span className="status" data-status={mission.status}>{mission.status}</span></div><h2>{mission.title}</h2><p>{catalyst?.event || 'Catalyst'} · {complete}/{Math.max(checkpoints.length, 1)} checkpoints</p><button onClick={() => navigateToCatalyst(mission.catalystId)}>Open War Room</button></article>; })}</div> : <EmptyCard title="No Active Missions" subtitle="A mission can begin from any shared catalyst when deeper research is warranted." />}</section>
      <section><div className="section-heading"><div><h2>Members</h2><p>Workspace roles control shared research only.</p></div><button className="text-button" onClick={() => navigate('/settings')}>Manage Access <ArrowRight size={15} /></button></div><div className="card member-list">{workspace.workspaceMembers.map((member) => <div key={member.userId}><MemberBadge initials={member.initials} name={member.displayName} /><span>{member.workspaceRole === 'owner' ? 'Workspace owner' : 'Workspace member'}</span></div>)}</div>
        <div className="section-heading"><div><h2>Open Questions</h2><p>What the desk still needs to resolve.</p></div></div>{openQuestions.length ? <div className="card question-list">{openQuestions.slice(0, 6).map((question) => { const author = memberLabel(workspace.workspaceMembers, question.createdBy); return <div key={question.id}><CircleHelp size={16} /><p><b>{question.question}</b><span>Asked by {author.name}</span></p></div>; })}</div> : <EmptyCard title="No Open Questions" subtitle="Questions created in a War Room will collect here." />}</section></div>
    <section><div className="section-heading"><div><h2>Recent Shared Activity</h2><p>Only allowlisted research events appear here—never balances, fills, risk, or journal content.</p></div></div>{workspace.activity.length ? <div className="card activity-list">{workspace.activity.slice(0, 12).map((event) => { const actor = memberLabel(workspace.workspaceMembers, event.actorId); return <div key={event.id}><MemberBadge initials={actor.initials} name={actor.name} compact /><p><b>{event.summary}</b><span>{new Date(event.createdAt).toLocaleString()}</span></p><CheckCircle2 size={15} /></div>; })}</div> : <EmptyCard title="No Shared Activity Yet" subtitle="Evidence, missions, thesis responses, and shared forecasts will appear here." />}</section>
  </div>;
}
