import { useEffect, useRef, useState, type CSSProperties, type PropsWithChildren, type TouchEvent } from 'react';
import { Menu, Moon, Plus, Settings, Sun, Users, X } from 'lucide-react';
import { navigate, primaryNavigation, swipeNavigationTarget, type AppPath } from '../../config/navigation';
import { CloudAccount } from '../CloudAccount';

function NavLink({ path, current, compact = false, onClick }: { path: typeof primaryNavigation[number]['path']; current: AppPath; compact?: boolean; onClick?: () => void }) {
  const item = primaryNavigation.find((candidate) => candidate.path === path)!; const Icon = item.icon;
  return <a href={`#${item.path}`} className={current === item.path ? 'active' : ''} aria-current={current === item.path ? 'page' : undefined} onClick={onClick}><Icon size={compact ? 20 : 18} /><span>{item.label}</span></a>;
}

export function AppShell({ current, dark, userId, email, onTheme, onBuildIdea, onRefresh, children }: PropsWithChildren<{ current: AppPath; dark: boolean; userId?: string; email?: string; onTheme: () => void; onBuildIdea: () => void; onRefresh: () => void }>) {
  const [more, setMore] = useState(false);
  const primaryIndex = primaryNavigation.findIndex((item) => item.path === current); const mobileSlotIndex = primaryIndex >= 0 ? primaryIndex : primaryNavigation.length;
  const [navPosition, setNavPosition] = useState(mobileSlotIndex); const [navDragging, setNavDragging] = useState(false);
  const swipe = useRef<{ x: number; y: number; active: boolean; slot: number; index: number }>({ x: 0, y: 0, active: false, slot: 52, index: -1 });
  const suppressTap = useRef(false);
  const secondaryCurrent = current === '/workspace' ? { label: 'Workspace', icon: Users } : current === '/settings' ? { label: 'Settings', icon: Settings } : undefined;
  const MobileMoreIcon = more ? X : secondaryCurrent?.icon || Menu;
  useEffect(() => { setNavPosition(more ? primaryNavigation.length : mobileSlotIndex); }, [mobileSlotIndex, more]);
  const startSwipe = (event: TouchEvent<HTMLElement>) => { const touch = event.touches[0]; if (!touch || primaryIndex < 0) return; const width = Math.max(1, (event.currentTarget.getBoundingClientRect().width - 10) / (primaryNavigation.length + 1)); swipe.current = { x: touch.clientX, y: touch.clientY, active: true, slot: width, index: primaryIndex }; suppressTap.current = false; setNavDragging(true); };
  const moveSwipe = (event: TouchEvent<HTMLElement>) => { const touch = event.touches[0]; if (!touch || !swipe.current.active) return; const x = touch.clientX - swipe.current.x; const y = touch.clientY - swipe.current.y; if (Math.abs(y) > Math.abs(x) + 8) { swipe.current.active = false; setNavDragging(false); setNavPosition(mobileSlotIndex); return; } setNavPosition(Math.max(0, Math.min(primaryNavigation.length - 1, swipe.current.index + x / swipe.current.slot))); };
  const endSwipe = (event: TouchEvent<HTMLElement>) => { const touch = event.changedTouches[0]; const distance = touch && swipe.current.active ? touch.clientX - swipe.current.x : 0; const target = swipeNavigationTarget(current, distance, swipe.current.slot); swipe.current.active = false; setNavDragging(false); if (Math.abs(distance) >= 24) { suppressTap.current = true; window.setTimeout(() => { suppressTap.current = false; }, 350); } if (!target) { setNavPosition(mobileSlotIndex); return; } setNavPosition(primaryNavigation.findIndex((item) => item.path === target)); setMore(false); navigate(target); };
  return <div className="app-shell">
    <a className="skip-link" href="#main-content">Skip to content</a>
    <aside className="sidebar"><img src={`${import.meta.env.BASE_URL}brand/oj-logo-primary-light.svg`} alt="OJ" /><nav aria-label="Primary">{primaryNavigation.map((item) => <NavLink key={item.path} path={item.path} current={current} />)}</nav><button className="build-button" onClick={onBuildIdea}><Plus size={17} />Build Idea</button><nav className="secondary-navigation" aria-label="Workspace"><a href="#/workspace" className={current === '/workspace' ? 'active' : ''}><Users size={18} /><span>Workspace</span></a></nav><div className="sidebar-note"><b>Private research</b><span>No brokerage access</span></div></aside>
    <main id="main-content"><header className="topbar"><div><span className="eyebrow">Options Journey</span><strong>{primaryNavigation.find((item) => item.path === current)?.label || (current === '/workspace' ? 'Workspace' : current === '/settings' ? 'Settings' : 'Overview')}</strong></div><div className="top-actions">{userId && email && <CloudAccount userId={userId} email={email} onRefresh={onRefresh} />}<button className="icon-button" onClick={onTheme} aria-label={dark ? 'Use light mode' : 'Use dark mode'}>{dark ? <Sun /> : <Moon />}</button><button className="icon-button" onClick={() => navigate('/settings')} aria-label="Open settings"><Settings /></button></div></header>{children}</main>
    <nav className="mobile-nav" aria-label="Mobile primary navigation. Drag the glass selection or tap a section." data-dragging={navDragging ? 'true' : undefined} style={{ '--nav-position': `${navPosition * 100}%` } as CSSProperties} onTouchStart={startSwipe} onTouchMove={moveSwipe} onTouchEnd={endSwipe} onTouchCancel={() => { swipe.current.active = false; setNavDragging(false); setNavPosition(mobileSlotIndex); }} onClickCapture={(event) => { if (!suppressTap.current) return; event.preventDefault(); event.stopPropagation(); suppressTap.current = false; }}>{primaryNavigation.map((item) => <NavLink key={item.path} path={item.path} current={current} compact />)}<button className={more || secondaryCurrent ? 'active' : ''} onClick={() => setMore(!more)} aria-expanded={more} aria-label={more ? 'Close more navigation' : secondaryCurrent ? `Open more navigation. Current section: ${secondaryCurrent.label}` : 'Open more navigation'}><MobileMoreIcon /><span>{secondaryCurrent?.label || 'More'}</span></button></nav>
    {more && <div className="more-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) setMore(false); }}><section className="more-sheet" role="dialog" aria-label="More navigation"><header><b>More</b><button className="icon-button" onClick={() => setMore(false)} aria-label="Close more navigation"><X /></button></header><nav><a href="#/workspace" className={current === '/workspace' ? 'active' : ''} onClick={() => setMore(false)}><Users size={18} /><span>Workspace</span></a><a href="#/settings" className={current === '/settings' ? 'active' : ''} onClick={() => setMore(false)}><Settings size={18} /><span>Settings</span></a></nav><button className="build-button" onClick={() => { setMore(false); onBuildIdea(); }}><Plus size={17} />Build Idea</button></section></div>}
  </div>;
}

export function PageHeader({ title, subtitle, action }: { title: string; subtitle: string; action?: React.ReactNode }) {
  return <header className="page-header"><div><h1>{title}</h1><p>{subtitle}</p></div>{action}</header>;
}
