import { useEffect, useLayoutEffect, useRef, useState, type CSSProperties, type PropsWithChildren, type TouchEvent } from 'react';
import { Menu, Moon, Plus, Settings, Sun, Users, X } from 'lucide-react';
import { navigate, normalizeMobileNavigation, primaryNavigation, swipeNavigationTarget, type AppPath, type PrimaryPath } from '../../config/navigation';
import { CloudAccount } from '../CloudAccount';

function NavLink({ path, current, compact = false, onClick }: { path: typeof primaryNavigation[number]['path']; current: AppPath; compact?: boolean; onClick?: () => void }) {
  const item = primaryNavigation.find((candidate) => candidate.path === path)!; const Icon = item.icon;
  return <a href={`#${item.path}`} className={current === item.path ? 'active' : ''} aria-current={current === item.path ? 'page' : undefined} data-mobile-nav-slot={compact ? '' : undefined} onClick={onClick}><Icon size={compact ? 20 : 18} /><span>{item.label}</span></a>;
}

type MobileNavGeometry = { origin: number; step: number; width: number };

export function AppShell({ current, dark, compactCards = false, mobileNavigation, userId, email, onTheme, onBuildIdea, onRefresh, children }: PropsWithChildren<{ current: AppPath; dark: boolean; compactCards?: boolean; mobileNavigation?: PrimaryPath[]; userId?: string; email?: string; onTheme: () => void; onBuildIdea: () => void; onRefresh: () => void }>) {
  const [more, setMore] = useState(false);
  const mobilePaths = normalizeMobileNavigation(mobileNavigation); const mobileItems = mobilePaths.map((path) => primaryNavigation.find((item) => item.path === path)!);
  const mobileIndex = mobilePaths.findIndex((path) => path === current); const mobileSlotIndex = mobileIndex >= 0 ? mobileIndex : mobileItems.length;
  const hiddenPrimary = primaryNavigation.filter((item) => !mobilePaths.includes(item.path));
  const [navPosition, setNavPosition] = useState(mobileSlotIndex); const [navDragging, setNavDragging] = useState(false);
  const mobileNavRef = useRef<HTMLElement>(null); const [mobileNavGeometry, setMobileNavGeometry] = useState<MobileNavGeometry>();
  const swipe = useRef<{ x: number; y: number; active: boolean; slot: number; index: number }>({ x: 0, y: 0, active: false, slot: 52, index: -1 });
  const suppressTap = useRef(false);
  const hiddenPrimaryCurrent = hiddenPrimary.find((item) => item.path === current); const secondaryCurrent = current === '/workspace' ? { label: 'Workspace', icon: Users } : current === '/settings' ? { label: 'Settings', icon: Settings } : undefined; const overflowCurrent = hiddenPrimaryCurrent || secondaryCurrent;
  const MobileMoreIcon = more ? X : overflowCurrent?.icon || Menu;
  useEffect(() => { setNavPosition(more ? mobileItems.length : mobileSlotIndex); }, [mobileItems.length, mobileSlotIndex, more]);
  useLayoutEffect(() => { const nav = mobileNavRef.current; if (!nav) return; const measure = () => { const slots = nav.querySelectorAll<HTMLElement>('[data-mobile-nav-slot]'); if (slots.length < 2) return; const navRect = nav.getBoundingClientRect(); const first = slots[0].getBoundingClientRect(); const second = slots[1].getBoundingClientRect(); setMobileNavGeometry({ origin: first.left + first.width / 2 - (navRect.left + navRect.width / 2), step: second.left + second.width / 2 - (first.left + first.width / 2), width: Math.max(1, first.width - 4) }); }; measure(); const observer = typeof ResizeObserver === 'undefined' ? undefined : new ResizeObserver(measure); observer?.observe(nav); window.addEventListener('resize', measure); return () => { observer?.disconnect(); window.removeEventListener('resize', measure); }; }, []);
  const mobileNavStyle = { '--nav-indicator-shift': `${mobileNavGeometry ? mobileNavGeometry.origin + navPosition * mobileNavGeometry.step : 0}px`, '--nav-indicator-width': `${mobileNavGeometry?.width || 0}px`, '--nav-indicator-opacity': mobileNavGeometry ? '1' : '0' } as CSSProperties;
  const startSwipe = (event: TouchEvent<HTMLElement>) => { const touch = event.touches[0]; if (!touch || mobileIndex < 0) return; const width = Math.max(1, mobileNavGeometry?.step || (event.currentTarget.getBoundingClientRect().width - 10) / (mobileItems.length + 1)); swipe.current = { x: touch.clientX, y: touch.clientY, active: true, slot: width, index: mobileIndex }; suppressTap.current = false; setNavDragging(true); };
  const moveSwipe = (event: TouchEvent<HTMLElement>) => { const touch = event.touches[0]; if (!touch || !swipe.current.active) return; const x = touch.clientX - swipe.current.x; const y = touch.clientY - swipe.current.y; if (Math.abs(y) > Math.abs(x) + 8) { swipe.current.active = false; setNavDragging(false); setNavPosition(mobileSlotIndex); return; } setNavPosition(Math.max(0, Math.min(mobileItems.length - 1, swipe.current.index + x / swipe.current.slot))); };
  const endSwipe = (event: TouchEvent<HTMLElement>) => { const touch = event.changedTouches[0]; const distance = touch && swipe.current.active ? touch.clientX - swipe.current.x : 0; const target = swipeNavigationTarget(current, distance, swipe.current.slot, 24, mobilePaths); swipe.current.active = false; setNavDragging(false); if (Math.abs(distance) >= 24) { suppressTap.current = true; window.setTimeout(() => { suppressTap.current = false; }, 350); } if (!target) { setNavPosition(mobileSlotIndex); return; } setNavPosition(mobilePaths.findIndex((path) => path === target)); setMore(false); navigate(target); };
  return <div className="app-shell" data-card-density={compactCards ? 'compact' : 'comfortable'}>
    <a className="skip-link" href="#main-content">Skip to content</a>
    <aside className="sidebar"><img src={`${import.meta.env.BASE_URL}brand/oj-logo-primary-light.svg`} alt="OJ" /><nav aria-label="Primary">{primaryNavigation.map((item) => <NavLink key={item.path} path={item.path} current={current} />)}</nav><button className="build-button" onClick={onBuildIdea}><Plus size={17} />Build Idea</button><nav className="secondary-navigation" aria-label="Workspace"><a href="#/workspace" className={current === '/workspace' ? 'active' : ''}><Users size={18} /><span>Workspace</span></a></nav><div className="sidebar-note"><b>Private research</b><span>No brokerage access</span></div></aside>
    <main id="main-content"><header className="topbar"><div><span className="eyebrow">Options Journey</span><strong>{primaryNavigation.find((item) => item.path === current)?.label || (current === '/workspace' ? 'Workspace' : current === '/settings' ? 'Settings' : 'Overview')}</strong></div><div className="top-actions">{userId && email && <CloudAccount userId={userId} email={email} onRefresh={onRefresh} />}<button className="icon-button" onClick={onTheme} aria-label={dark ? 'Use light mode' : 'Use dark mode'}>{dark ? <Sun /> : <Moon />}</button><button className="icon-button" onClick={() => navigate('/settings')} aria-label="Open settings"><Settings /></button></div></header>{children}</main>
    <nav ref={mobileNavRef} className="mobile-nav" aria-label="Mobile primary navigation. Drag the glass selection or tap a section." data-dragging={navDragging ? 'true' : undefined} style={mobileNavStyle} onTouchStart={startSwipe} onTouchMove={moveSwipe} onTouchEnd={endSwipe} onTouchCancel={() => { swipe.current.active = false; setNavDragging(false); setNavPosition(mobileSlotIndex); }} onClickCapture={(event) => { if (!suppressTap.current) return; event.preventDefault(); event.stopPropagation(); suppressTap.current = false; }}>{mobileItems.map((item) => <NavLink key={item.path} path={item.path} current={current} compact />)}<button data-mobile-nav-slot="" className={more || overflowCurrent ? 'active' : ''} onClick={() => setMore(!more)} aria-expanded={more} aria-label={more ? 'Close more navigation' : overflowCurrent ? `Open more navigation. Current section: ${overflowCurrent.label}` : 'Open more navigation'}><MobileMoreIcon /><span>{overflowCurrent?.label || 'More'}</span></button></nav>
    {more && <div className="more-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) setMore(false); }}><section className="more-sheet" role="dialog" aria-label="More navigation"><header><b>More</b><button className="icon-button" onClick={() => setMore(false)} aria-label="Close more navigation"><X /></button></header><nav>{hiddenPrimary.map((item) => <NavLink key={item.path} path={item.path} current={current} onClick={() => setMore(false)} />)}<a href="#/workspace" className={current === '/workspace' ? 'active' : ''} onClick={() => setMore(false)}><Users size={18} /><span>Workspace</span></a><a href="#/settings" className={current === '/settings' ? 'active' : ''} onClick={() => setMore(false)}><Settings size={18} /><span>Settings</span></a></nav><button className="build-button" onClick={() => { setMore(false); onBuildIdea(); }}><Plus size={17} />Build Idea</button></section></div>}
  </div>;
}

export function PageHeader({ title, subtitle, action }: { title: string; subtitle: string; action?: React.ReactNode }) {
  return <header className="page-header"><div><h1>{title}</h1><p>{subtitle}</p></div>{action}</header>;
}
