import { CopyPlus, MessageSquare, Share2, X } from 'lucide-react';
import { useState } from 'react';
import { forkSharedThesis, respondToSharedThesis, shareIdeaThesis } from '../data/collaboration-actions';
import { memberLabel } from '../data/collaboration';
import type { SharedThesis, TradeIdea, Workspace } from '../types/domain';
import { MemberBadge } from './MemberBadge';
import { EmptyCard } from './cards';

function safeStrategy(idea: TradeIdea) { return idea.strategy.toLowerCase().includes('bear') ? 'bear-put-spread' : 'bull-call-spread'; }

export function SharedThesisPanel({ workspace, onSaved }: { workspace: Workspace; onSaved: () => void | Promise<void> }) {
  const [idea, setIdea] = useState<TradeIdea>(); const [summary, setSummary] = useState(''); const [move, setMove] = useState(''); const [confidence, setConfidence] = useState('');
  const [response, setResponse] = useState<{ thesis: SharedThesis; body: string }>(); const [busy, setBusy] = useState(''); const [message, setMessage] = useState('');
  const share = async () => { if (!idea || !workspace.researchWorkspace) return; setBusy('share'); try { await shareIdeaThesis({ workspaceId: workspace.researchWorkspace.id, idea, catalystId: idea.catalystId, thesisSummary: summary, expectedMoveSummary: move, confidence: confidence ? Number(confidence) : undefined }); setIdea(undefined); setSummary(''); setMove(''); setConfidence(''); setMessage('Thesis shared without private risk or trade details.'); await onSaved(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Thesis could not be shared.'); } finally { setBusy(''); } };
  const reply = async () => { if (!response) return; setBusy('reply'); try { await respondToSharedThesis({ sharedThesisId: response.thesis.id, workspaceId: response.thesis.workspaceId, responseType: 'comment', body: response.body }); setResponse(undefined); await onSaved(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Response could not be saved.'); } finally { setBusy(''); } };
  const fork = async (thesis: SharedThesis) => { setBusy(thesis.id); try { await forkSharedThesis(thesis.id); setMessage(`${thesis.ticker} copied into your private Ideas.`); await onSaved(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Private copy could not be created.'); } finally { setBusy(''); } };
  return <section className="shared-thesis-section"><div className="section-heading"><div><h2>Shared Theses</h2><p>Compare conclusions while keeping trade structures, risk, and private notes personal.</p></div>{workspace.ideas.length > 0 && workspace.researchWorkspace && <button onClick={() => setIdea(workspace.ideas[0])}><Share2 size={15} />Share Thesis</button>}</div>
    {message && <p className="page-message" role="status">{message}</p>}
    {workspace.sharedTheses.length ? <div className="three-grid">{workspace.sharedTheses.map((thesis) => { const author = memberLabel(workspace.workspaceMembers, thesis.authorId); const responses = workspace.sharedThesisResponses.filter((item) => item.sharedThesisId === thesis.id); return <article className="card shared-thesis-card" key={thesis.id}><header><MemberBadge initials={author.initials} name={author.name} /><span className="status">{thesis.bias}</span></header><div><span className="eyebrow">{thesis.strategy}</span><h2>{thesis.ticker}</h2><p>{thesis.thesisSummary}</p>{thesis.expectedMoveSummary && <small>Expected move: {thesis.expectedMoveSummary}</small>}</div><footer><span>{responses.length} response{responses.length === 1 ? '' : 's'}</span><div><button aria-label={`Respond to ${thesis.ticker}`} onClick={() => setResponse({ thesis, body: '' })}><MessageSquare size={15} /></button><button onClick={() => void fork(thesis)} disabled={busy === thesis.id}><CopyPlus size={15} />Private Copy</button></div></footer></article>; })}</div> : <EmptyCard title="No Shared Theses" subtitle="Sharing is optional. Your private Ideas remain complete when you work alone." />}
    {idea && <div className="modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget && !busy) setIdea(undefined); }}><section className="share-dialog card" role="dialog" aria-modal="true" aria-labelledby="share-thesis-title"><header><div><span className="eyebrow">Safe share preview</span><h2 id="share-thesis-title">Share a thesis—not a trade</h2></div><button className="icon-button" aria-label="Close" onClick={() => setIdea(undefined)}><X /></button></header><label><span>Private idea</span><select value={idea.id} onChange={(event) => setIdea(workspace.ideas.find((item) => item.id === event.target.value) || idea)}>{workspace.ideas.map((item) => <option key={item.id} value={item.id}>{item.ticker} · {item.strategy}</option>)}</select></label><div className="safe-preview" aria-label="Fields that will be shared"><h3>Only these fields will be shared</h3><dl><div><dt>Ticker</dt><dd>{idea.ticker}</dd></div><div><dt>Bias</dt><dd>{idea.bias}</dd></div><div><dt>Strategy</dt><dd>{safeStrategy(idea)}</dd></div><div><dt>Summary</dt><dd>{summary || 'Add below'}</dd></div><div><dt>Expected move</dt><dd>{move || 'Optional'}</dd></div><div><dt>Confidence</dt><dd>{confidence ? `${confidence}%` : 'Optional'}</dd></div></dl><p>Candidate strikes, account values, risk limits, entries, exits, and private notes are excluded.</p></div><label><span>Thesis summary</span><textarea value={summary} onChange={(event) => setSummary(event.target.value)} /></label><label><span>Expected move summary</span><input value={move} onChange={(event) => setMove(event.target.value)} placeholder="Optional" /></label><label><span>Confidence (0–100)</span><input type="number" min="0" max="100" value={confidence} onChange={(event) => setConfidence(event.target.value)} /></label><footer><button onClick={() => setIdea(undefined)}>Keep Private</button><button className="primary" disabled={!summary.trim() || busy === 'share'} onClick={() => void share()}><Share2 size={15} />{busy === 'share' ? 'Sharing' : 'Share Safe Fields'}</button></footer></section></div>}
    {response && <div className="modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget && !busy) setResponse(undefined); }}><section className="share-dialog compact-dialog card" role="dialog" aria-modal="true" aria-labelledby="respond-title"><header><div><span className="eyebrow">Shared response</span><h2 id="respond-title">Respond to {response.thesis.ticker}</h2></div><button className="icon-button" aria-label="Close" onClick={() => setResponse(undefined)}><X /></button></header><label><span>Comment</span><textarea autoFocus value={response.body} onChange={(event) => setResponse({ ...response, body: event.target.value })} /></label><footer><button onClick={() => setResponse(undefined)}>Cancel</button><button className="primary" disabled={!response.body.trim() || busy === 'reply'} onClick={() => void reply()}>Post Response</button></footer></section></div>}
  </section>;
}
