total_account_capital: 1200
options_allocation: 200
normal_max_loss_per_trade_min: 40
normal_max_loss_per_trade_max: 50
absolute_max_loss_per_trade: 60
maximum_simultaneous_spreads: 1
default_expiration_days_min: 30
default_expiration_days_max: 60
preferred_strategies:
  - bull-call-spread
  - bear-put-spread
