import { useEffect, useState } from 'react';
import { HashRouter, NavLink, Route, Routes } from 'react-router-dom';
import { motion, useReducedMotion } from 'framer-motion';
import { Activity, BarChart3, BookOpen, CalendarDays, ChevronRight, ClipboardCheck, Lightbulb, Settings, ShieldCheck, Target } from 'lucide-react';
import { Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Workflow, SyncMark } from './components/Workflow';

type Trade={id:string;ticker:string;strategy:string;status:string;bias:string;confidence:string;plannedEntry:string;plannedExitBefore:string;expiration:string;catalysts:string[];candidates:{name:string;width:string;debit:string;risk:string;summary:string}[];fields:Record<string,string>};
type Catalyst={date:string;event:string;sensitivity:string;holdThrough:string;ticker:string};
const nav=[['/', 'Overview',Activity],['/trade-ideas','Trade ideas',Lightbulb],['/active-trades','Active',Target],['/closed-trades','Closed',ClipboardCheck],['/research','Research',BookOpen],['/catalysts','Catalysts',CalendarDays],['/analytics','Analytics',BarChart3],['/journal','Journal',BookOpen],['/settings','Settings',Settings]] as const;
const load=<T,>(name:string)=>fetch(`${import.meta.env.BASE_URL}data/${name}.json`).then(r=>r.json() as Promise<T>);
const dollars=(value:number|null|undefined)=>value==null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(value);

function Shell({children}:{children:React.ReactNode}){const [dark,setDark]=useState(true),[wizard,setWizard]=useState(false); useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';},[dark]);return <div className="shell"><aside className="sidebar"><img className="logo" src={`${import.meta.env.BASE_URL}brand/oj-logo-primary-light.svg`} alt="OJ — Options Journey"/><nav>{nav.map(([to,label,Icon])=><NavLink key={to} to={to} end={to==='/' }><Icon size={18}/><span>{label}</span></NavLink>)}</nav><button className="new-trade" onClick={()=>setWizard(true)}><PlusIcon/> New trade idea</button><div className="privacy"><ShieldCheck size={17}/><span>Research only<br/>No brokerage access</span></div></aside><main><header className="topbar"><div><span className="eyebrow">Private decision journal</span><strong>Options Journey</strong></div><div className="top-actions"><SyncMark state="published"/><button className="theme" onClick={()=>setDark(!dark)} aria-label="Toggle color theme">{dark?'Light mode':'Dark mode'}</button></div></header>{children}</main><nav className="mobile-nav">{nav.slice(0,5).map(([to,label,Icon])=><NavLink key={to} to={to} end={to==='/' } aria-label={label}><Icon size={19}/></NavLink>)}</nav><Workflow open={wizard} onClose={()=>setWizard(false)}/></div>}
const PlusIcon=()=> <span aria-hidden="true">＋</span>;
function RiskRing({used=0,limit=200}:{used?:number;limit?:number}){const p=Math.max(.03,used/limit);return <div className="risk"><div className="ring" style={{background:`conic-gradient(var(--orange) ${p*360}deg,var(--pulp) 0deg)`}}><div><b>{dollars(used)}</b><span>at risk</span></div></div><p>of {dollars(limit)} options allocation</p></div>}
function Layout({title,kicker,children}:{title:string;kicker:string;children:React.ReactNode}){const reduced=useReducedMotion();return <motion.section className="page" initial={reduced?false:{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{duration:.24}}><div className="page-heading"><div><span className="eyebrow">{kicker}</span><h1>{title}</h1></div></div>{children}</motion.section>}
function Overview({trade,catalysts}:{trade:Trade; catalysts:Catalyst[]}){return <Layout title="A clearer record of every decision." kicker="Overview"><div className="hero-grid"><section className="hero panel"><div><span className="eyebrow">Capital context</span><h2>$1,200 <small>total account</small></h2><p>Defined-risk research with an intentionally small options allocation.</p></div><RiskRing/><div className="metrics"><Metric label="Options allocation" value="$200"/><Metric label="Available" value="$200"/><Metric label="Realized P&L" value="—"/><Metric label="Unrealized P&L" value="—"/></div></section><section className="panel journey"><span className="eyebrow">Journey progress</span><h2>One idea, properly documented.</h2><div className="pipeline">{['Research','Watchlist','Ready','Active','Closed','Reviewed'].map((item,i)=><div className={i===1?'current':''} key={item}><i>{i+1}</i>{item}</div>)}</div></section></div><div className="two-col"><section className="panel idea"><div className="section-title"><div><span className="eyebrow">Current trade idea</span><h2>{trade.ticker} bull call spread</h2></div><span className="badge">Watchlist</span></div><p>Moderately bullish through late August, conditional on the market’s post-jobs reaction—not a forecast treated as fact.</p><div className="detail-row"><span>Entry after</span><b>Jobs report · Aug 7</b><span>Exit before</span><b>NVIDIA earnings · Aug 26</b></div><NavLink className="text-link" to="/trade-ideas">Review candidate structures <ChevronRight size={16}/></NavLink></section><section className="panel"><span className="eyebrow">Upcoming catalysts</span><h2>What could change the thesis</h2><div className="catalyst-list">{catalysts.map(c=><div key={c.event}><b>{c.date.slice(5).replace('-','/')}</b><span>{c.event}<small>{c.sensitivity} sensitivity · {c.holdThrough}</small></span></div>)}</div></section></div><div className="two-col"><section className="panel"><span className="eyebrow">Recent journal lesson</span><h2>Process before outcome.</h2><p>A profitable trade can still be reckless; a defined-risk loss can still be well executed. OJ records both separately.</p></section><section className="panel rules"><span className="eyebrow">Rule adherence</span><h2>Baseline guardrails</h2><p>One spread · limit orders · no averaging down · no expiration holds.</p></section></div></Layout>}
const Metric=({label,value}:{label:string;value:string})=><div><span>{label}</span><b>{value}</b></div>;
function TradeIdeas({trade}:{trade:Trade}){return <Layout title="Trade ideas" kicker="Research pipeline"><section className="panel trade-card"><div className="section-title"><div><span className="eyebrow">{trade.bias} · {trade.confidence} confidence</span><h2>{trade.ticker} · Bull call spread</h2></div><span className="badge">Watchlist</span></div><p>Enter only after the jobs report if SPY holds or recovers, yields remain contained, and both legs offer acceptable liquidity.</p><div className="compare">{trade.candidates.map((c,i)=><article className={i?'candidate':'candidate featured'} key={c.name}><span className="eyebrow">{c.name}</span><h3>{c.width}-wide</h3><p>{c.summary}</p><dl><div><dt>Target debit</dt><dd>{c.debit}</dd></div><div><dt>Risk</dt><dd>{c.risk}</dd></div><div><dt>Final strikes</dt><dd>TBD</dd></div></dl></article>)}</div></section><section className="panel"><span className="eyebrow">Invalidation</span><h2>When the setup weakens</h2><ul><li>SPY breaks post-jobs support and fails to recover.</li><li>Treasury yields rise sharply or the inflation/rates narrative shifts.</li><li>Pricing exceeds the defined-risk plan.</li></ul></section></Layout>}
function EmptyPage({title,copy,icon:Icon}:{title:string;copy:string;icon:typeof Activity}){return <Layout title={title} kicker="Journal workspace"><section className="empty panel"><Icon size={32}/><h2>Nothing to analyze yet.</h2><p>{copy}</p></section></Layout>}
function Catalysts({catalysts}:{catalysts:Catalyst[]}){return <Layout title="Catalyst calendar" kicker="Sensitivity map"><section className="panel"><div className="calendar">{catalysts.map(c=><article key={c.event}><b>{c.date}</b><h3>{c.event}</h3><p>{c.ticker} · {c.sensitivity} sensitivity</p><span>{c.holdThrough}</span></article>)}</div></section></Layout>}
function Analytics(){const data=[{n:'Research',v:84},{n:'Entry',v:0},{n:'Sizing',v:100},{n:'Exit',v:0}];return <Layout title="Analytics" kicker="Process, not just profit"><div className="two-col"><section className="panel"><span className="eyebrow">Process score</span><h2>Awaiting an executed trade.</h2><p>No outcome is inferred from a thesis. Add confirmed entries, exits, and reviews to unlock analytics.</p></section><section className="panel chart"><ResponsiveContainer width="100%" height={200}><LineChart data={data}><XAxis dataKey="n" stroke="currentColor"/><YAxis stroke="currentColor"/><Tooltip/><Line dataKey="v" stroke="#ff8a30" strokeWidth={3}/></LineChart></ResponsiveContainer></section></div></Layout>}
function App(){const [trade,setTrade]=useState<Trade>();const [catalysts,setCatalysts]=useState<Catalyst[]>([]),[loading,setLoading]=useState(true);useEffect(()=>{load<Trade[]>('trades').then(t=>setTrade(t[0]));load<Catalyst[]>('catalysts').then(setCatalysts);const t=setTimeout(()=>setLoading(false),1600);return()=>clearTimeout(t)},[]);if(!trade||loading)return <div className="loading"><div className="juice"><img src={`${import.meta.env.BASE_URL}brand/oj-logo-mark-white.svg`} alt="OJ"/><i/><b/><b/></div><span>Preparing your journal…</span></div>;return <HashRouter><Shell><Routes><Route path="/" element={<Overview trade={trade} catalysts={catalysts}/>}/><Route path="/trade-ideas" element={<TradeIdeas trade={trade}/>}/><Route path="/active-trades" element={<EmptyPage title="Active trades" copy="A trade appears here only after you explicitly confirm an actual fill." icon={Target}/>}/><Route path="/closed-trades" element={<EmptyPage title="Closed trades" copy="Closed positions and process reviews will be preserved here." icon={ClipboardCheck}/>}/><Route path="/research" element={<EmptyPage title="Research" copy="Macro and ticker research notes will appear as structured, sanitized context." icon={BookOpen}/>}/><Route path="/catalysts" element={<Catalysts catalysts={catalysts}/>}/><Route path="/analytics" element={<Analytics/>}/><Route path="/journal" element={<EmptyPage title="Journal" copy="Review original thesis, execution, discipline, and lessons after each completed trade." icon={BookOpen}/>}/><Route path="/settings" element={<EmptyPage title="Settings" copy="Theme, data freshness, and privacy preferences remain local-first." icon={Settings}/>}/></Routes></Shell></HashRouter>}
export default App;
