create extension if not exists pgcrypto;
create type public.oj_sync_status as enum ('local_draft','cloud_draft','submitted','formalization_pending','pull_request_open','changes_requested','validated','merged','publishing','published','failed','conflict','archived');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, email text, approved boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.trade_ideas (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id), ticker text not null, strategy text not null check(strategy in ('bull-call-spread','bear-put-spread')), bias text not null, confidence text, data jsonb not null default '{}', revision integer not null default 1 check(revision>0), sync_status public.oj_sync_status not null default 'cloud_draft', published_record_id uuid, published_commit_sha text, published_note_path text, last_submitted_at timestamptz, last_published_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);
create table public.trade_candidates (id uuid primary key default gen_random_uuid(), trade_idea_id uuid not null references public.trade_ideas(id) on delete cascade, user_id uuid not null references public.profiles(id), name text not null check(name in ('Balanced','Aggressive')), data jsonb not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.catalysts (id uuid primary key default gen_random_uuid(), trade_idea_id uuid references public.trade_ideas(id) on delete set null, user_id uuid not null references public.profiles(id), event text not null, event_type text not null, event_at timestamptz, data jsonb not null default '{}', revision integer not null default 1, sync_status public.oj_sync_status not null default 'cloud_draft', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);
create table public.research_annotations (id uuid primary key default gen_random_uuid(), trade_idea_id uuid references public.trade_ideas(id) on delete cascade, user_id uuid not null references public.profiles(id), classification text not null, summary text not null, data jsonb not null default '{}', revision integer not null default 1, sync_status public.oj_sync_status not null default 'cloud_draft', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);
create table public.trade_entries (id uuid primary key default gen_random_uuid(), trade_idea_id uuid not null references public.trade_ideas(id), user_id uuid not null references public.profiles(id), data jsonb not null, confirmed_actual boolean not null default false, revision integer not null default 1, sync_status public.oj_sync_status not null default 'cloud_draft', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.trade_checkins (id uuid primary key default gen_random_uuid(), trade_idea_id uuid not null references public.trade_ideas(id), user_id uuid not null references public.profiles(id), data jsonb not null, revision integer not null default 1, sync_status public.oj_sync_status not null default 'cloud_draft', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.trade_exits (id uuid primary key default gen_random_uuid(), trade_idea_id uuid not null references public.trade_ideas(id), user_id uuid not null references public.profiles(id), data jsonb not null, confirmed_actual boolean not null default false, revision integer not null default 1, sync_status public.oj_sync_status not null default 'cloud_draft', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.journal_reviews (id uuid primary key default gen_random_uuid(), trade_idea_id uuid not null references public.trade_ideas(id), user_id uuid not null references public.profiles(id), ratings jsonb not null default '{}', data jsonb not null default '{}', revision integer not null default 1, sync_status public.oj_sync_status not null default 'cloud_draft', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.formalization_jobs (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id), record_type text not null, record_id uuid not null, payload_revision integer not null, idempotency_key text not null unique, status public.oj_sync_status not null default 'submitted', github_run_id bigint, pr_number integer, pr_url text, branch text, note_path text, error text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.formalization_payloads (id uuid primary key default gen_random_uuid(), job_id uuid not null unique references public.formalization_jobs(id) on delete cascade, user_id uuid not null references public.profiles(id), payload jsonb not null, payload_hash text not null, created_at timestamptz not null default now());
create table public.sync_events (id bigint generated always as identity primary key, user_id uuid not null references public.profiles(id), record_type text not null, record_id uuid not null, event text not null, revision integer, metadata jsonb not null default '{}', created_at timestamptz not null default now());
create table public.published_records (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id), record_type text not null, record_id uuid not null, note_path text not null, commit_sha text not null, pr_number integer, merged_at timestamptz, created_at timestamptz not null default now(), unique(record_type,record_id));
create function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,email,approved) values(new.id,new.email,false) on conflict(id) do nothing; return new; end $$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create index on public.trade_ideas(user_id); create index on public.catalysts(user_id); create index on public.research_annotations(user_id); create index on public.formalization_jobs(user_id); create index on public.sync_events(user_id,created_at desc);
alter table public.profiles enable row level security; alter table public.trade_ideas enable row level security; alter table public.trade_candidates enable row level security; alter table public.catalysts enable row level security; alter table public.research_annotations enable row level security; alter table public.trade_entries enable row level security; alter table public.trade_checkins enable row level security; alter table public.trade_exits enable row level security; alter table public.journal_reviews enable row level security; alter table public.formalization_jobs enable row level security; alter table public.formalization_payloads enable row level security; alter table public.sync_events enable row level security; alter table public.published_records enable row level security;

create function public.is_approved_user() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles where id=auth.uid() and approved) $$;
do $$ declare t text; begin foreach t in array array['trade_ideas','trade_candidates','catalysts','research_annotations','trade_entries','trade_checkins','trade_exits','journal_reviews'] loop execute format('create policy %I on public.%I for select using (auth.uid()=user_id and public.is_approved_user())',t||'_select',t); execute format('create policy %I on public.%I for insert with check (auth.uid()=user_id and public.is_approved_user())',t||'_insert',t); execute format('create policy %I on public.%I for update using (auth.uid()=user_id and public.is_approved_user()) with check (auth.uid()=user_id and public.is_approved_user())',t||'_update',t); execute format('create policy %I on public.%I for delete using (auth.uid()=user_id and public.is_approved_user())',t||'_delete',t); end loop; end $$;
create policy profiles_self_select on public.profiles for select using(auth.uid()=id); create policy profiles_self_update on public.profiles for update using(auth.uid()=id) with check(auth.uid()=id);
create policy jobs_owner_select on public.formalization_jobs for select using(auth.uid()=user_id and public.is_approved_user());
create policy payloads_owner_select on public.formalization_payloads for select using(auth.uid()=user_id and public.is_approved_user());
create policy events_owner_select on public.sync_events for select using(auth.uid()=user_id and public.is_approved_user());
create policy published_owner_select on public.published_records for select using(auth.uid()=user_id and public.is_approved_user());
revoke update(user_id) on public.trade_ideas,public.trade_candidates,public.catalysts,public.research_annotations,public.trade_entries,public.trade_checkins,public.trade_exits,public.journal_reviews from authenticated;
revoke update(id,approved) on public.profiles from authenticated;
